### ISSUE TITLE
Scoreboard view

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/MarketSim#41]
Maybe we should sort students according to their current balance in the monitor view to make it more like a "Scoreboard"?

**Comment by dybber** [comment]
I guess a usecase is for teachers to screenshare the monitor on a projector, and in that case perhaps only the scoreboard should be visible, but market parameters shouldn't. I guess we should have a chat about the design of the monitor page

**Comment by KristianMSchmidt** [comment]
It sound like a good idea to sort by balance - it will no doubt make the experience more engaging. So far, I've basically just made all data visible on the monitor view  - in part because it's nice during development, when doing manual debugging. Hiding stuff later is easy. 

We should also discuss how to show show balance in the table for players who have joined the market late or missed a round. I have some suggestions for this...
