### ISSUE TITLE
Represent balances and other amounts in Øre internally

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/MarketSim#50]

**Comment by KristianMSchmidt** [comment]
I'm having doubts about this issue. Is the nice integer representation in Øre worth the trouble of re-implementing the Django modelForms and doing all the translation back and forth between øre and kroner?  Wouldn't it be okay to represent amounts in kroner everywhere and store these amounts in the database as decimal numbers with a fixed number of decimals (1 or 2 should do)? Rounding errors should not occur with this solution as we only subtract and add amounts (and multiply them by integers).

**Comment by dybber** [comment]
Is it really that complex? It's only when it's displayed to the user that it needs to be converted to Øre, and when the values from the forms are read, that it needs to be converted back. I guess two functions for conversion needs to be written, and they need to be applied in various places across the code, but I don't see it as a difficult problem, but perhaps I'm wrong?

**Comment by KristianMSchmidt** [comment]
The thing is that I have implemented all the forms as "model forms". This is a nice thing to do when the data types in the models and the forms are the same, since forms in this case will be defined and validated automatically. However, if we want float values in the forms and integers in the model it is no longer a good idea as we then have to "hack" into the process and change the input values before validation of the form. So either we should implement such as hack or reimplement the forms as plain Django forms not associated to models. I will take a few days off and then reconsider...

**Comment by dybber** [comment]
Ok, let's talk about it monday

**Comment by KristianMSchmidt** [comment]
When googling questions such as "what is the best way to represent price/money/currency" in a Django model, most people seem to suggest a DecimalField with 2 decimals. Perhaps I've been biased in my search...?

Eg: https://stackoverflow.com/questions/1139393/what-is-the-best-django-model-field-to-use-to-represent-a-us-dollar-amount
