### ISSUE TITLE
Create account - no feed back / error messages on creation

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/MarketSim#68]
When I tried to create and account I was just send back to the same page (the form), and no error message was shown. All fields except the password fields retained their content.

**Comment by KristianMSchmidt** [comment]
Client side validation errors are clearly shown in Chrome, but perhaps not so much in other browsers. 

An easy solution to this problem is to simple disable client side validation in the create account form and rely on (only) server side validation instead. This can be achieved by adding the word "novalidate" to the form tag.
